name: Deploy to Cloudflare Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    uses: Minicon-eG/.github/.github/workflows/deploy-static-site.yml@main
    with:
      site_name: felsland-grundschule
      domain: felsland-grundschule.minicon.eu
      cloudflare_pages_project: website-felsland-grundschule
    secrets: inherit
